### ISSUE TITLE
Main mic not working during a call and in voice recorder.  

### ISSUE THREAD

**Issue by vishwanathan-iyer** [bgcngm/android_device_xiaomi_gemini#2]
The main mic is not working during a call and in voice recorder. I tried microphone amplifier, increased gain by 50 but only noise. I can very faintly hear myself when very close to the speaker. I do not suspect a hardware problem since my phone is only two weeks old. Is there any fix in software available ?
Changing build.prop and disabling fluence doesn't seem to work. Please suggest other solutions.

**Comment by bgcngm** [comment]
Please refer to the Mi5Devs repo. This is no longer updated here.
